cat/checksystem/checkapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("",home),
    path("register",registerchecker),
    path("select",select), 
    path("delete/<int:id>",delete),
    path("update/<int:id>",update),
    path("login",login),   
]

cat/checksystem/checksystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('checkapp.urls')),
]

cat/checksystem/checkapp/models.py
from django.db import models

# Create your models here.

class checking(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    phone = models.IntegerField()
    role = models.CharField(max_length = 50)
    device_name = models.CharField(max_length = 50)
    device_type = models.CharField(max_length = 50)
    serial_number = models.CharField(max_length = 50)
    time_in = models.DateTimeField()

    def _str_(self):
        return self.first_name


class check_record(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    phone = models.IntegerField()
    role = models.CharField(max_length = 50)
    device_name = models.CharField(max_length = 50)
    device_type = models.CharField(max_length = 50)
    serial_number = models.CharField(max_length = 50)
    time_in = models.CharField(max_length = 250)
    time_out = models.DateTimeField()

    def _str_(self):
        return self.first_name

class checker(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    password = models.CharField(max_length = 50)
    phone = models.IntegerField()
    
    def _str_(self):
        return self.first_name

cat/checksystem/checkapp/forms.py
from django import forms
from .models import *

class writechecker(forms.ModelForm):
    class Meta:
        model = checker
        fields = ('__all__')


class checkin(forms.ModelForm):
    class Meta:
        model = checking
        fields = ('__all__')

        
class checkout(forms.ModelForm):
    class Meta:
        model = check_record
        fields = ('__all__')

cat/checksystem/checkapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from .forms import *
# Create your views here.

def home(request):
    return render(request,"home.html")

def select(request):
    userdata = checking.objects.all()
    print(userdata)
    insertdata = checkin() 
    if(request.method == "POST"):
        form = checkin(request.POST)
        if(form.is_valid()):
            form.save()
            return redirect('/select')
    else:
        insertdata = checkin()
        return render(request,"select.html",{"formu":insertdata,"userdata":userdata})
    
 
def registerchecker(request):
    insert = writechecker()
    if(request.method == "POST"):
        form = writechecker(request.POST)
        if(form.is_valid()):
            form.save()
            return redirect('/login')
    else:
        insert = writechecker()
        return render(request,"registerfchecker.html",{"myform":insert})




def delete(request,id):
    id=id
    x = checking.objects.get(id = id)
    print(x.first_name)
    form =checkout()
    print()
    if(request.method == 'POST'):
        form = checkout(request.POST)
        if(form.is_valid()):
            form.save()
            x.delete()
            return redirect('/select')
    else:
        form = checkout()  
    cont = {'done': x,'fini': form}  
    return render(request,'del.html',cont)
  
 
def update(request, id):
    info = checking.objects.get(id = id)
    if(request.method == 'POST'):
        form = checkin(request.POST,instance = info)
        if(form.is_valid()):
            info.save()
            return redirect('/select')
    else:
        form = checkin(instance = info)
    cont = {'done': form,'fini': info}
    return render(request,"update.html",cont)

    
def login(request):
    if(request.method == 'POST'):
        phone = request.POST.get("phone")
        password = request.POST.get("password")
        userdata = checker.objects.filter(phone =phone,password = password)
        if(len(userdata)>0):
            return redirect('/select')
        else:
            return render(request,'login.html',{"notdata":"<b> you are not registed!</b>"})
        
    return render(request,'login.html',{"notdata":"<b> you are not registed!</b>"})
    
    

cat/checksystem/checkapp/templates/del.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<style>
    body{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    form{
        margin-top: 25%;
        display: flex;
        flex-direction: row;
        justify-content: center;
        font-size: 29px;
    }
    .edit{
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        font-size: 29px;
    
    }
    .edit input{
        width: 300px;
    }
    form input[type="submit"]{
        width: 250px;

    }
</style>
<body class="bg-dark text-white">
    <!-- <form action="" method="post">
        {% csrf_token %}
        {{ forma.as_p }}
        
         
        <input type="submit" value="delete">
        </form> -->

       <form action="" method="post">
        {% csrf_token %}<div style="display: none;">
            <label for="id_first_name">First name:</label>
            <input type="text" name="first_name" maxlength="50" value="{{done.first_name}}" required id="id_first_name">
            </div>
            <div style="display: none;">
            <label for="id_last_name">Last name:</label>
                <input type="text" name="last_name" maxlength="50" value="{{done.last_name}}" required id="id_last_name">
           </div>        
          <div style="display: none;">
            <label for="id_phone">Phone:</label>
        <input type="number" name="phone" value="{{done.phone}}" required id="id_phone">
            </div>
            <div style="display: none;">
            <label for="id_role">Role:</label>
        <input type="text" name="role" maxlength="50" value="{{done.role}} " required id="id_role">
           </div>
           <div style="display: none;">
            <label for="id_device_name">Device name:</label>
        <input type="text" name="device_name" maxlength="50" value="{{done.device_name}}" required id="id_device_name">
          </div>
           <div style="display: none;">
            <label for="id_device_type">Device type:</label>
        <input type="text" name="device_type" maxlength="50" value="{{done.device_type}}" required id="id_device_type">
                </div>
            <div style="display: none;">
            <label for="id_serial_number">Serial number:</label>        
        <input type="text" name="serial_number" maxlength="50" required id="id_serial_number" value="{{done.serial_number}} ">
                </div >
             <div style="display: none;">
            <label for="id_time_in">Time in:</label>
        <input type="text" name="time_in" required id="id_time_in" value="{{done.time_in}}">
                </div>
        <div class="edit">
            <label for="id_time_out">TIME OUT:</label>
        <input class="mx-3" type="datetime-local" name="time_out" value="" required id="id_time_out">
             
        </div>

        <input type="submit" style="font-size: 29px" class="btn btn-success mx-3" value="CHECK OUT">
    </form> 
</body>
</html>

cat/checksystem/checkapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CHECK SYSTEM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static style.css %}">
</head>
<style>
body{
    background-color: #e0f3fa;
}
h1{
    font-size: 50px;
    margin-top: 170px;
    margin-left: 170px;
}
.check{
    text-decoration: none ;
    padding: 20px 40px;
    background-color: deepskyblue;
    color: white;
    float: right;
    font-size: 40px;
    border-radius: 300px;
}
p{
    width: 700px;
    font-size: 20px;
    padding: 10px ;
}
marquee div{
    display: flex;
    flex-direction: row;
}
marquee div div{
    width: 300px;
    height: 35px;
    display: flex;
    flex-direction: row;
}
.blue{
    background-color: blue;
}
.red{
    background-color: red;
}
.yellow{
    background-color: yellow;
}
.gray{
    background-color: gray;
}
</style>
<body>
    <h1>WELCOME TO <br >CHECKSYSTEM</h1>
    <a href="/login" class="check">CHECK</a>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, sequi. Molestiae, minus recusandae velit tempore nemo cupiditate voluptates fugiat ut consequatur voluptas nisi, ratione sit facilis expedita iusto perferendis at.</p>
    <!-- <img src="{% static 'back.jpg' %}" width ="100%" alt="" srcset=""> -->
    <marquee behavior="" direction="alternative" width = "1000px">
        <div>
        <div class = "blue"></div>
        <div class = "red"></div>
        <div class = "yellow"></div>
        <div class = "gray"></div>
        </div>
    </marquee>
    
</body>
</html>

cat/checksystem/checkapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<style>
    body{
        display: flex;
        flex-direction: column;
        justify-content: space-around;
        align-items: center;
    }
    .form{
        margin-top: 10%;
        width: 400px;
        display: flex;
        flex-direction: column;
        border: 2px solid white;
        padding: 10px 20px;
    }
    .form div{
        display: flex;
        flex-direction: row;
        justify-content: space-between;
    }
    .form div input[type="submit"]{
        width: 170px;
        font-weight: 700;
    }
    h1{
        width: 100%;
        text-align: center;
    }
    .text{
        text-decoration: none;
        color: rgb(16, 173, 173);
        font-size: 20px;
        cursor: pointer;
    }

</style>
<body class="bg-dark text-white">
    <form action="" method="post" class="form">
        <h1>LOGIN</h1>
        {% csrf_token %}
        <label for="phone" class="pt-3 pb-3"> PHONE:</label><input type="text" name="phone">
        <label for="password" class="pt-2 pb-3">PASSWORD:</label><input class="pt-2" type="password" name="password">
        <div>
            <input class="btn btn-success my-3" type="submit" value="LOGIN">
            <a href="/register" class="btn btn-primary my-3">CREATE ACCOUNT</a>
        </div>

        <a class="text">Forget password</a>
    </form>
</body>
</html>

cat/checksystem/checkapp/templates/registerfchecker.html
<!DOCTYPE html>
<html lang="en">
    {% load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>REGISTER CHECKER</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<style>
    body{
        display: flex;
        flex-direction: column;
        justify-items: center;
        align-items: center;
    }
    form{
        margin-top: 50px;
        width: 500px;
        display: flex;
        flex-direction: column;
        justify-items: center;
        align-items: center;
        border: 2px solid gray;
    }
    form div{
        width: 100%;
        display: flex;
        flex-direction: column;
        justify-items: center;
        align-items: center;
        
    }
    form input{
        width: 250px;
    }
    form div input[type="submit"]{
        width: 60%;
        height: 40px;
        margin: 20px;
        color: aliceblue;
        font-weight: 700;
        border: 2px solid rgb(38, 124, 38);
        border-radius: 10px;
        background-color: rgb(38, 124, 38);
    }
    form div input[type="submit"]:hover{
        background-color: rgb(57, 153, 57);
    }
    form label{
        color: white;
        margin-right: 15px;
        padding: 10px;
    
    }
    form label[for="id_phone"]{
        margin-right: 45px;
    }
    form label[for="id_password"]{
        margin-right: 23px;
    }

</style>
<body class="bg-dark text-white">

    <form action="" method="POST" class="form">
        <h1>CREATE ACCOUNT</h1>
        {% csrf_token %}
        {{ myform.as_p }}
        <div>
        <input type="submit" value="REGISTER">
    </div>
    </form>
    
</body>
</html>

cat/checksystem/checkapp/templates/select.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>RECORDS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<style>
form {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 400px;
    height: 500px;

}
form .all{
    
    display: flex;
    flex-direction: space-between;
}
form input[type="submit"]{
    display: block;
    width:300px;
    
}
form input{
    width: 400px;
}
table{
    border-collapse: 1px;
}
.hee{
    width: 100%;
    height: 60px;
    background-color: rgb(134, 37, 218);
    display: flex;
    flex-direction: space-around;
    align-items: center;
}
form div select{
    width: 401px;
}
.table{
    background-color: gray;
}
.search{
    width: 100%;
}
.fom{
    width: 100%;
    height: 100px;
    display: flex;
    flex-direction: row;
    justify-items: center;
    align-items: center;
    padding-left: 200px;
}

</style>
<body class="bg-dark text-white"> 
<div class=" hee  ">
    <span >CHECKSYSTEM</span>
    <div>user name
        <img src="" alt="" srcset="">
    </div>
    <div>
        <a class=" btn btn-primary" href="/">LOGOUT</a>
    </div>
</div>

    <form action="" method="post" class="container">
        {% csrf_token %}
        <div class="all">
            <div>
                <div>
                <label for="id_first_name" class="pt-3 pb-3 ">First name:</label>
                <input type="text" name="first_name" maxlength="50" value="" required id="id_first_name">
                </div>
                <div class="pt-3  ">
                <label for="id_last_name" class="pt-3 pb-3 ">Last name:</label>
                    <input type="text" name="last_name" maxlength="50" value="" required id="id_last_name">
               </div>        
              <div class="pt-3">
                <label for="id_phone" class="pt-3 pb-3 ">Phone:</label><br>
            <input type="number" name="phone" value="" required id="id_phone">
                </div>
                    <div class="pt-2 pb-3 my-3 ">
                    <label for="id_role" class="pt-2 pb-2 ">Role:</label><br>
                     <select name="role" maxlength="50" value="" required   id="id_role">
                        <option value="">CHOOSE THE ROLE..</option>
                        <option value="STAFF">STAFF</option>
                        <option value="STUDENT">STUDENT</option>
                        <option value="OUT SIDER">OUT SIDER</option>
                        </select>
                       </div>
                </div>
            <div>
               
               <div class="pt-3 pb-3 ">
                <label for="id_device_name" class="pt-2 pb-2 ">Device name:</label>
            <input type="text" name="device_name" maxlength="50" value="" required id="id_device_name">
              </div>
               <div>
                <label for="id_device_type" class="pt-3 pb-3 ">Device type:</label>
            <input type="text" name="device_type" maxlength="50" value="" required id="id_device_type">
                    </div>
                <div class="pt-3 pb-3 ">
                <label for="id_serial_number" class="pt-3 pb-3 ">Serial number:</label> <br>       
            <input type="text" name="serial_number" maxlength="50" required id="id_serial_number" value="">
                    </div>
                 <div class="pt-1 pb-2 ">
                <label for="id_time_in"class="pt-0 pb-3" >Time in: </label><br>
            <input type="datetime-local" name="time_in" required id="id_time_in" value="">
                    </div>
                </div>
        </div>
         <input class="btn btn-success text-white pt-3 pb-3 " type="submit" value="CHECK IN">
    </form>

<div class="search">
    <form class="fom" method="get" action="">
        <input type="text" name="serial_number">
        <input class="btn btn-success" type="submit" value="SEARCH">
    </form>
    
</div>




    <table  class="table" >
        <tr>
            <th class="col">First name</th>
            <th>Last name</th>
            <th>Phone</th>
            <th>Role</th>
            <th>Device name</th>
            <th>Device type</th>
            <th>Serial number</th>
            <th>Time in</th>
            <th colspan="2">ACTION</th>
        </tr>

        {% for data in userdata %}
        <tr>
            <td>{{data.first_name}}</td>
            <td>{{data.last_name}}</td>
            <td>{{data.phone}}</td>
            <td>{{data.role}}</td>
            <td>{{data.device_name}}</td>
            <td>{{data.device_type}}</td>
            <td>{{data.serial_number}}</td>
            <td>{{data.time_in}}</td>
            <td><a class = "my-3 btn btn-secondary" href="/delete/{{data.id}}">CHECK OUT</a></td>
            <td><a class = "my-3 btn btn-primary" href="/update/{{data.id}}">UPDATE</a></td>
            
        </tr>

        {% endfor %}
    </table>


     
  
    
</body>
</html>

cat/checksystem/checkapp/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<style>body{
    display: flex;
    flex-direction: column;
    justify-items: center;
    align-items: center;
}
form{
    margin-top: 50px;
    width: 500px;
    display: flex;
    flex-direction: column;
    justify-items: center;
    align-items: center;
    border: 2px solid gray;
}
form div{
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-items: center;
    align-items: center;
    
}
form input{
    width: 250px;
}
form div input[type="submit"]{
    width: 60%;
    height: 40px;
    margin: 20px;
    color: aliceblue;
    font-weight: 700;
    border: 2px solid rgb(38, 124, 38);
    border-radius: 10px;
    background-color: rgb(38, 124, 38);
}
form div input[type="submit"]:hover{
    background-color: rgb(57, 153, 57);
}
form label{
    color: white;
    margin-right: 15px;
    padding: 10px;

}
form label[for="id_phone"]{
    margin-right: 45px;
}
form label[for="id_role"]{
    margin-right: 62px;
}
form label[for="id_time_in"]{
    margin-right: 55px;
}
form label[for="id_serial_number"]{
    margin-right: 9px;
}
form label[for="id_device_type"]{
    margin-right: 19px;
}
form label[for="id_device_name"]{
    margin-right: 9px;
}


</style>
<body class="bg-dark ">
    <form action="" method="post">
    {% csrf_token %}
    {{ done.as_p }}
    <input class="btn btn-primary" style="margin: 10px;" type="submit" value="UPDATE">
    </form>
    
</body>
</html>